### PR TITLE
Extract metrics reloaded as a submodule

### PR DESCRIPTION
**Pull request by RamSaw**

### CODE REVIEW

**Comment by RamSaw** [comment]
@Snyssfx is it ready to be reviewed and merged or you still need to commit some changes? 
Seems like travis is unable to download MetricsReloaded.

**Comment by Snyssfx** [comment]
@RamSaw oops, didn't see that there is travis CI, wait a few minutes, I will try to fix it

**Comment by Snyssfx** [comment]
@RamSaw there it is. Change ssh to https url for submodule.

**Comment by Snyssfx** [comment]
As for commiting some changes, I added [Readme.md](urlhttps://github.com/ml-in-programming/MetricsReloaded-gradle/blob/e59a95411191a72ef87e2fbbbc00d9d904c9765d/README.md) to MetricsReloaded-gradle with instructions (for other projects) how to build submodule

**Comment by Snyssfx** [comment]
@RamSaw as I know, it's one of git submodules limitations. After clonning, you should execute in bash `git submodule update --init --recursive`.
If you check Travis logs, you will probably find this command after `git clone ...`

**Comment by Snyssfx** [comment]
@RamSaw well, in [this commit](https://github.com/ml-in-programming/ArchitectureReloaded/pull/170/commits/709496c552acefd2b12b7be10be30533d224e514) I have added `submoduleUpdate` gradle task, but my attempts to link it to building process was unsuccessful :(
You can launch it manually, however

**Pull request merged**
